export const environment = {
  production: true,
  url: "https://api.pals.africa/api/",
  payStackCheckoutUrl: `https://api.pals.africa/api/securewithpaystack`,
  payStackReleaseUrl: `https://api.pals.africa/api/initiateRelease/`,
  processPayoutUrl: `https://api.pals.africa/api/processbusinesspayout`,
  checkTransactionStatusUrl: `https://api.pals.africa/api/chektransactionstatus`,
  addAccountUrl: `https://api.pals.africa/api/createrecipient/`,
  updateAccountUrl: `https://api.pals.africa/api/updateuseraccount/`,
  createTransactionUrl: `https://api.pals.africa/api/newtransaction`,
  deleteAccountUrl: `https://api.pals.africa/api/deleteduseraccount`,
  getTransactionByIdUrl: `https://api.pals.africa/api/getusertransaction/`,
  getTransactionsListUrl: `https://api.pals.africa/api/getmerchanttransactions/`,
  verifyReleaseCodeUrl: `https://api.pals.africa/api/verifycode`,
  cancelTransactionUrl: `https://api.pals.africa/api/cancelescrowtransaction/`,
  getBusinessUserPayoutsUrl: `https://api.pals.africa/api/getbusinessuserpayouts/`,
  getBusinessTransactionsSummaryUrl: `https://api.pals.africa/api/getusertransactionssummary/`,
  updateDeliveyUrl: `https://api.pals.africa/api/updatedeliveryphone`,
  getUserAccountDetailsUrl: `https://api.pals.africa/api/getbusinessuseraccountdetails/`,
  registerPalUserUrl: `https://api.pals.africa/api/registerpaluser`,
  registerUserUrl: `https://api.pals.africa/api/register`,
  loginUrl:`https://api.pals.africa/api/login`,

  addBusinessUrl: `https://api.pals.africa/api/addbusiness`,
  getModulesDataUrl: `https://api.pals.africa/api/getmodulesdata`,
  getBusinessDataUrl: `https://api.pals.africa/api/getuserbusiness/`,
  createTransferUrl: `https://api.pals.africa/api/createtransfer`,
  requestTopUpUrl: `https://api.pals.africa/api/requesttopup`,
  getUserTopUpsUrl: `https://api.pals.africa/api/getusertopups/`,
  getUserBalancesUrl: `https://api.pals.africa/api/getbusinessuserbalances/`
};
