export const environment = {
  production: true,
  url: "https://api.noworri.com/api/",
  payStackCheckoutUrl: `https://api.noworri.com/api/securewithpaystack`,
  payStackReleaseUrl: `https://api.noworri.com/api/initiateRelease/`,
  processPayoutUrl: `https://api.noworri.com/api/processbusinesspayout`,
  checkTransactionStatusUrl: `https://api.noworri.com/api/chektransactionstatus`,
  addAccountUrl: `https://api.noworri.com/api/createrecipient/`,
  updateAccountUrl: `https://api.noworri.com/api/updateuseraccount/`,
  createTransactionUrl: `https://api.noworri.com/api/newtransaction`,
  deleteAccountUrl: `https://api.noworri.com/api/deleteduseraccount`,
  getTransactionByIdUrl: `https://api.noworri.com/api/getusertransaction/`,
  getTransactionsListUrl: `https://api.noworri.com/api/usertransactions/`,
  verifyReleaseCodeUrl: `https://api.noworri.com/api/verifycode`,
  cancelTransactionUrl: `https://api.noworri.com/api/cancelescrowtransaction/`,
  getBusinessUserPayoutsUrl: `https://api.noworri.com/api/getbusinessuserpayouts/`,
  getBusinessTransactionsSummaryUrl: `https://api.noworri.com/api/getusertransactionssummary/`,
  updateDeliveyUrl: `https://api.noworri.com/api/updatedeliveryphone`,
  getUserAccountDetailsUrl: `https://api.noworri.com/api/getbusinessuseraccountdetails/`,
  registerPalUserUrl: `https://api.noworri.com/api/registerpaluser`
};
